# Generated by Django 3.2.8 on 2021-10-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
