# Generated by Django 3.2.8 on 2021-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Cli_email',
            new_name='cli_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Cli_id',
            new_name='cli_id',
        ),
    ]
