# Generated by Django 3.2.8 on 2021-10-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211013_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
