# Generated by Django 3.2.8 on 2021-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_order',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_count', models.CharField(max_length=20)),
                ('item_location', models.CharField(max_length=20)),
                ('item_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
