# Generated by Django 3.2.8 on 2021-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_place_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=30)),
                ('expiry_month', models.CharField(max_length=10)),
                ('expiry_year', models.CharField(max_length=10)),
            ],
        ),
    ]
